# imports_layout = "HorizontalVertical"
# Stable
reorder_imports = true
format_strings = true
imports_indent = "Block"
imports_layout = "Mixed"
newline_style = "Unix"
edition = "2018"
fn_args_layout = "Compressed"
max_width = 80
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
imports_granularity = "Crate"
# Unstable
format_code_in_doc_comments = true
wrap_comments = true

